//blogs

export const FETCH_BLOGS_START = "FETCH_BLOG_START";
export const FETCH_BLOGS_FAIL = "FETCH_BLOG_FAIL";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOG_SUCCESS";
export const REMOVE_BLOGS_ERRORS = "REMOVE_BLOG_ERRORS";

export const FETCH_SINGLE_BLOG_START = "FETCH_SINGLE_BLOG_START";
export const FETCH_SINGLE_BLOG_FAIL = "FETCH_SINGLE_BLOG_FAIL";
export const FETCH_SINGLE_BLOG_SUCCESS = "FETCH_SINGLE_BLOG_SUCCESS";
export const REMOVE_SINGLE_BLOG_ERRORS = "REMOVE_SINGLE_BLOG_ERRORS";

//projects

export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const REMOVE_PROJECTS_ERRORS = "REMOVE_PROJECTS_ERRORS";

//works

export const FETCH_WORKS_START = "FETCH_WORKS_START";
export const FETCH_WORKS_FAIL = "FETCH_WORKS_FAIL";
export const FETCH_WORKS_SUCCESS = "FETCH_WORKS_SUCCESS";
export const REMOVE_WORKS_ERRORS = "REMOVE_WORKS_ERRORS";
