//language

export const ENGLISH = "ENGLISH";
export const KURDISH = "KURDISH";
export const ARABIC = "ARABIC";

//BLOGS

export const GET_ALL_BLOG_START = "GET_ALL_BLOG_START";
export const GET_ALL_BLOG_FAIL = "GET_ALL_BLOG_FAIL";
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS";

export const GET_HOME_BLOG_START = "GET_HOME_BLOG_START";
export const GET_HOME_BLOG_FAIL = "GET_HOME_BLOG_FAIL";
export const GET_HOME_BLOG_SUCCESS = "GET_HOME_BLOG_SUCCESS";

export const GET_ONE_BLOG_START = "GET_ONE_BLOG_START";
export const GET_ONE_BLOG_FAIL = "GET_ONE_BLOG_FAIL";
export const GET_ONE_BLOG_SUCCESS = "GET_ONE_BLOG_SUCCESS";

export const CREATE_BLOG_START = "CREATE_BLOG_START";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";

export const DELETE_BLOG_START = "DELETE_BLOG_START";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";

export const UPDATE_BLOG_START = "UPDATE_BLOG_START";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";

//PROJECTS

export const GET_ALL_PROJECT_START = "GET_ALL_PROJECT_START";
export const GET_ALL_PROJECT_FAIL = "GET_ALL_PROJECT_FAIL";
export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";

export const CREATE_PROJECT_START = "CREATE_PROJECT_START";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";

export const DELETE_PROJECT_START = "DELETE_PROJECT_START";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";

export const UPDATE_PROJECT_START = "UPDATE_PROJECT_START";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";

//WORK

export const GET_ALL_WORK_START = "GET_ALL_WORK_START";
export const GET_ALL_WORK_FAIL = "GET_ALL_WORK_FAIL";
export const GET_ALL_WORK_SUCCESS = "GET_ALL_WORK_SUCCESS";

export const CREATE_WORK_START = "CREATE_WORK_START";
export const CREATE_WORK_FAIL = "CREATE_WORK_FAIL";
export const CREATE_WORK_SUCCESS = "CREATE_WORK_SUCCESS";

export const DELETE_WORK_START = "DELETE_WORK_START";
export const DELETE_WORK_FAIL = "DELETE_WORK_FAIL";
export const DELETE_WORK_SUCCESS = "DELETE_WORK_SUCCESS";

export const UPDATE_WORK_START = "UPDATE_WORK_START";
export const UPDATE_WORK_FAIL = "UPDATE_WORK_FAIL";
export const UPDATE_WORK_SUCCESS = "UPDATE_WORK_SUCCESS";

//ADMIN
export const LOAD_USER = "LOAD_USER";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GET_ALL_ADMINS_START = "GET_ALL_ADMINS_START";
export const GET_ALL_ADMINS_FAIL = "GET_ALL_ADMINS_FAIL";
export const GET_ALL_ADMINS_SUCCESS = "GET_ALL_ADMINS_SUCCESS";

export const CREATE_ADMIN_START = "CREATE_ADMIN_START";
export const CREATE_ADMIN_FAIL = "CREATE_ADMIN_FAIL";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";

export const DELETE_ADMIN_START = "DELETE_ADMIN_START";
export const DELETE_ADMIN_FAIL = "DELETE_ADMIN_FAIL";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";

export const UPDATE_ADMIN_START = "UPDATE_ADMIN_START";
export const UPDATE_ADMIN_FAIL = "UPDATE_ADMIN_FAIL";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";

//UNIVERSAL ERRORS AND SUCCESS

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const REMOVE_ALL_ERRORS = "REMOVE_ALL_ERRORS";
export const DECREASE_TIME = "DECREASE_TIME";

export const ADD_SUCCESS = "ADD_SUCCESS";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";
export const REMOVE_ALL_SUCCESS = "REMOVE_ALL_SUCCESS";
export const DECREASE_SUCCESS_TIME = "DECREASE_SUCCESS_TIME";

//IMAGES

export const BLOG_IMAGE = "BLOG_IMAGE";
export const BLOG_UPDATE_IMAGE = "BLOG_UPDATE_IMAGE";
export const PROJECT_IMAGE = "PROJECT_IMAGE";
export const PROJECT_UPDATE_IMAGE = "PROJECT_UPDATE_IMAGE";
export const ADMIN_IMAGE = "ADMIN_IMAGE";
export const ADMIN_UPDATE_IMAGE = "ADMIN_UPDATE_IMAGE";
export const WORK_IMAGE = "WORK_IMAGE";
export const WORK_UPDATE_IMAGE = "WORK_UPDATE_IMAGE";
