//ADMIN
export const AUTH_ADMIN = "AUTH_ADMIN";
export const AUTH_ERROR = "AUTH_ERROR";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

export const ADMIN_LOGOUT_START = "ADMIN_LOGOUT_START";
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";

export const GET_ALL_ADMINS_START = "GET_ALL_ADMINS_START";
export const GET_ALL_ADMINS_FAIL = "GET_ALL_ADMINS_FAIL";
export const GET_ALL_ADMINS_SUCCESS = "GET_ALL_ADMINS_SUCCESS";

export const GET_STORAGE_SIZE_START = "GET_STORAGE_SIZE_START";
export const GET_STORAGE_SIZE_FAIL = "GET_STORAGE_SIZE_FAIL";
export const GET_STORAGE_SIZE_SUCCESS = "GET_STORAGE_SIZE_SUCCESS";

export const ADD_ADMIN_START = "ADD_ADMIN_START";
export const ADD_ADMIN_FAIL = "ADD_ADMIN_FAIL";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";

export const DELETE_ADMIN_START = "DELETE_ADMIN_START";
export const DELETE_ADMIN_FAIL = "DELETE_ADMIN_FAIL";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";

export const UPDATE_ADMIN_START = "UPDATE_ADMIN_START";
export const UPDATE_ADMIN_FAIL = "UPDATE_ADMIN_FAIL";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
