export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REMOVE_ALL_ALERTS = "REMOVE_ALL_ALERTS";
export const DECREASE_ALERT_TIME = "DECREASE_ALERT_TIME";
export const TOGGLE_ALERT_SHOW = "TOGGLE_ALERT_SHOW";
