//BLOGS

export const GET_BLOGS_START = "GET_BLOGS_START";
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";

export const GET_ONE_BLOG_START = "GET_ONE_BLOG_START";
export const GET_ONE_BLOG_FAIL = "GET_ONE_BLOG_FAIL";
export const GET_ONE_BLOG_SUCCESS = "GET_ONE_BLOG_SUCCESS";

export const ADD_BLOG_START = "ADD_BLOG_START";
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL";
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";

export const DELETE_BLOG_START = "DELETE_BLOG_START";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";

export const UPDATE_BLOG_START = "UPDATE_BLOG_START";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
