//CERTIFICATES

export const GET_CERTIFICATES_START = "GET_CERTIFICATES_START";
export const GET_CERTIFICATES_FAIL = "GET_CERTIFICATES_FAIL";
export const GET_CERTIFICATES_SUCCESS = "GET_CERTIFICATES_SUCCESS";

export const GET_ONE_CERTIFICATE_START = "GET_ONE_CERTIFICATE_START";
export const GET_ONE_CERTIFICATE_FAIL = "GET_ONE_CERTIFICATE_FAIL";
export const GET_ONE_CERTIFICATE_SUCCESS = "GET_ONE_CERTIFICATE_SUCCESS";

export const ADD_CERTIFICATE_START = "ADD_CERTIFICATE_START";
export const ADD_CERTIFICATE_FAIL = "ADD_CERTIFICATE_FAIL";
export const ADD_CERTIFICATE_SUCCESS = "ADD_CERTIFICATE_SUCCESS";

export const DELETE_CERTIFICATE_START = "DELETE_CERTIFICATE_START";
export const DELETE_CERTIFICATE_FAIL = "DELETE_CERTIFICATE_FAIL";
export const DELETE_CERTIFICATE_SUCCESS = "DELETE_CERTIFICATE_SUCCESS";

export const UPDATE_CERTIFICATE_START = "UPDATE_CERTIFICATE_START";
export const UPDATE_CERTIFICATE_FAIL = "UPDATE_CERTIFICATE_FAIL";
export const UPDATE_CERTIFICATE_SUCCESS = "UPDATE_CERTIFICATE_SUCCESS";
