export const DELETE_ONE_CATEGORY_METHOD = "DELETE_ONE_CATEGORY_METHOD";
export const DELETE_ONE_PROJECT_METHOD = "DELETE_ONE_PROJECT_METHOD";
export const DELETE_ONE_WORK_METHOD = "DELETE_ONE_WORK_METHOD";
export const DELETE_ONE_STACK_METHOD = "DELETE_ONE_STACK_METHOD";
export const DELETE_ONE_TYPE_METHOD = "DELETE_ONE_TYPE_METHOD";
export const DELETE_ONE_SKILL_METHOD = "DELETE_ONE_SKILL_METHOD";
export const DELETE_ONE_CERTIFICATE_METHOD = "DELETE_ONE_CERTIFICATE_METHOD";
export const DELETE_ONE_ADMIN_METHOD = "DELETE_ONE_ADMIN_METHOD";
