export const BLOG_IMAGE = "BLOG_IMAGE";
export const INSIDE_BLOG_IMAGE = "INSIDE_BLOG_IMAGE";

export const UPLOAD_BLOG_IMAGE_START = "UPLOAD_BLOG_IMAGE_START";
export const UPLOAD_BLOG_IMAGE_FAIL = "UPLOAD_BLOG_IMAGE_FAIL";
export const UPLOAD_BLOG_IMAGE_SUCCESS = "UPLOAD_BLOG_IMAGE_SUCCESS";

export const UPLOAD_INNER_BLOG_IMAGE_START = "UPLOAD_INNER_BLOG_IMAGE_START";
export const UPLOAD_INNER_BLOG_IMAGE_FAIL = "UPLOAD_INNER_BLOG_IMAGE_FAIL";
export const UPLOAD_INNER_BLOG_IMAGE_SUCCESS =
  "UPLOAD_INNER_BLOG_IMAGE_SUCCESS";

export const DELETE_INNER_BLOG_IMAGE_START = "DELETE_INNER_BLOG_IMAGE_START";
export const DELETE_INNER_BLOG_IMAGE_FAIL = "DELETE_INNER_BLOG_IMAGE_FAIL";
export const DELETE_INNER_BLOG_IMAGE_SUCCESS =
  "DELETE_INNER_BLOG_IMAGE_SUCCESS";

export const PROJECT_IMAGE = "PROJECT_IMAGE";

export const UPLOAD_PROJECT_IMAGE_START = "UPLOAD_PROJECT_IMAGE_START";
export const UPLOAD_PROJECT_IMAGE_FAIL = "UPLOAD_PROJECT_IMAGE_FAIL";
export const UPLOAD_PROJECT_IMAGE_SUCCESS = "UPLOAD_PROJECT_IMAGE";

export const WORK_IMAGE = "WORK_IMAGE";

export const UPLOAD_WORK_IMAGE_START = "UPLOAD_WORK_IMAGE_START";
export const UPLOAD_WORK_IMAGE_FAIL = "UPLOAD_WORK_IMAGE_FAIL";
export const UPLOAD_WORK_IMAGE_SUCCESS = "UPLOAD_WORK_IMAGE";

export const SKILL_IMAGE = "SKILL_IMAGE";

export const UPLOAD_SKILL_IMAGE_START = "UPLOAD_SKILL_IMAGE_START";
export const UPLOAD_SKILL_IMAGE_FAIL = "UPLOAD_SKILL_IMAGE_FAIL";
export const UPLOAD_SKILL_IMAGE_SUCCESS = "UPLOAD_SKILL_IMAGE";

export const CERTIFICATE_IMAGE = "CERTIFICATE_IMAGE";

export const UPLOAD_CERTIFICATE_IMAGE_START = "UPLOAD_CERTIFICATE_IMAGE_START";
export const UPLOAD_CERTIFICATE_IMAGE_FAIL = "UPLOAD_CERTIFICATE_IMAGE_FAIL";
export const UPLOAD_CERTIFICATE_IMAGE_SUCCESS = "UPLOAD_CERTIFICATE_IMAGE";
