//PROJECTS

export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";

export const GET_ONE_PROJECT_START = "GET_ONE_PROJECT_START";
export const GET_ONE_PROJECT_FAIL = "GET_ONE_PROJECT_FAIL";
export const GET_ONE_PROJECT_SUCCESS = "GET_ONE_PROJECT_SUCCESS";

export const ADD_PROJECT_START = "ADD_PROJECT_START";
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";

export const DELETE_PROJECT_START = "DELETE_PROJECT_START";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";

export const UPDATE_PROJECT_START = "UPDATE_PROJECT_START";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
