//SKILL

export const GET_ALL_SKILL_START = "GET_ALL_SKILL_START";
export const GET_ALL_SKILL_FAIL = "GET_ALL_SKILL_FAIL";
export const GET_ALL_SKILL_SUCCESS = "GET_ALL_SKILL_SUCCESS";

export const ADD_SKILL_START = "ADD_SKILL_START";
export const ADD_SKILL_FAIL = "ADD_SKILL_FAIL";
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";

export const DELETE_SKILL_START = "DELETE_SKILL_START";
export const DELETE_SKILL_FAIL = "DELETE_SKILL_FAIL";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";

export const UPDATE_SKILL_START = "UPDATE_SKILL_START";
export const UPDATE_SKILL_FAIL = "UPDATE_SKILL_FAIL";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
