export const GET_ALL_STACK_START = "GET_ALL_STACK_START";
export const GET_ALL_STACK_FAIL = "GET_ALL_STACK_FAIL";
export const GET_ALL_STACK_SUCCESS = "GET_ALL_STACK_SUCCESS";

export const GET_ONE_STACK_START = "GET_ONE_STACK_START";
export const GET_ONE_STACK_FAIL = "GET_ONE_STACK_FAIL";
export const GET_ONE_STACK_SUCCESS = "GET_ONE_STACK_SUCCESS";

export const ADD_STACK_START = "ADD_STACK_START";
export const ADD_STACK_FAIL = "ADD_STACK_FAIL";
export const ADD_STACK_SUCCESS = "ADD_STACK_SUCCESS";

export const DELETE_STACK_START = "DELETE_STACK_START";
export const DELETE_STACK_FAIL = "DELETE_STACK_FAIL";
export const DELETE_STACK_SUCCESS = "DELETE_STACK_SUCCESS";

export const UPDATE_STACK_START = "UPDATE_STACK_START";
export const UPDATE_STACK_FAIL = "UPDATE_STACK_FAIL";
export const UPDATE_STACK_SUCCESS = "UPDATE_STACK_SUCCESS";
