//SUBSCRIBE

export const GET_ALL_SUBSCRIBE_START = "GET_ALL_SUBSCRIBE_START";
export const GET_ALL_SUBSCRIBE_FAIL = "GET_ALL_SUBSCRIBE_FAIL";
export const GET_ALL_SUBSCRIBE_SUCCESS = "GET_ALL_SUBSCRIBE_SUCCESS";

export const ADD_SUBSCRIBE_START = "ADD_SUBSCRIBE_START";
export const ADD_SUBSCRIBE_FAIL = "ADD_SUBSCRIBE_FAIL";
export const ADD_SUBSCRIBE_SUCCESS = "ADD_SUBSCRIBE_SUCCESS";

export const DELETE_SUBSCRIBE_START = "DELETE_SUBSCRIBE_START";
export const DELETE_SUBSCRIBE_FAIL = "DELETE_SUBSCRIBE_FAIL";
export const DELETE_SUBSCRIBE_SUCCESS = "DELETE_SUBSCRIBE_SUCCESS";
