export const GET_ALL_TYPE_START = "GET_ALL_TYPE_START";
export const GET_ALL_TYPE_FAIL = "GET_ALL_TYPE_FAIL";
export const GET_ALL_TYPE_SUCCESS = "GET_ALL_TYPE_SUCCESS";

export const GET_ONE_TYPE_START = "GET_ONE_TYPE_START";
export const GET_ONE_TYPE_FAIL = "GET_ONE_TYPE_FAIL";
export const GET_ONE_TYPE_SUCCESS = "GET_ONE_TYPE_SUCCESS";

export const ADD_TYPE_START = "ADD_TYPE_START";
export const ADD_TYPE_FAIL = "ADD_TYPE_FAIL";
export const ADD_TYPE_SUCCESS = "ADD_TYPE_SUCCESS";

export const DELETE_TYPE_START = "DELETE_TYPE_START";
export const DELETE_TYPE_FAIL = "DELETE_TYPE_FAIL";
export const DELETE_TYPE_SUCCESS = "DELETE_TYPE_SUCCESS";

export const UPDATE_TYPE_START = "UPDATE_TYPE_START";
export const UPDATE_TYPE_FAIL = "UPDATE_TYPE_FAIL";
export const UPDATE_TYPE_SUCCESS = "UPDATE_TYPE_SUCCESS";
