//WORK

export const GET_ALL_WORK_START = "GET_ALL_WORK_START";
export const GET_ALL_WORK_FAIL = "GET_ALL_WORK_FAIL";
export const GET_ALL_WORK_SUCCESS = "GET_ALL_WORK_SUCCESS";

export const ADD_WORK_START = "ADD_WORK_START";
export const ADD_WORK_FAIL = "ADD_WORK_FAIL";
export const ADD_WORK_SUCCESS = "ADD_WORK_SUCCESS";

export const DELETE_WORK_START = "DELETE_WORK_START";
export const DELETE_WORK_FAIL = "DELETE_WORK_FAIL";
export const DELETE_WORK_SUCCESS = "DELETE_WORK_SUCCESS";

export const UPDATE_WORK_START = "UPDATE_WORK_START";
export const UPDATE_WORK_FAIL = "UPDATE_WORK_FAIL";
export const UPDATE_WORK_SUCCESS = "UPDATE_WORK_SUCCESS";
