export const QUERY_KEYs = {
  //AUTH
  USER: "USER",

  //USER

  USERS: "USERS",

  //SKILL
  SKILLS: "SKILLS",
  //WORK
  WORKS: "WORKS",

  //PROJECTS

  PROJECTS: "PROJECTS",
  PROJECT: "PROJECT",
  SEARCH_PROJECTS: "SEARCH_PROJECTS",

  //CERTIFICATE
  CERTIFICATE: "CERTIFICATE",
  CERTIFICATES: "CERTIFICATES",
  SEARCH_CERTIFICATES: "SEARCH_CERTIFICATES",

  //BLOGS

  BLOGS: "BLOGS",
  RELATED_BLOGS: "RELATED_BLOGS",
  BLOG: "BLOG",
  SEARCH_BLOGS: "SEARCH_BLOGS",
  //SUBSCRIBERS

  SUBSCRIBERS: "SUBSCRIBERS",

  //CONFIG

  CATEGORIES: "CATEGORIES",
  STACKS: "STACKS",
  TYPES: "TYPES",
};
