export const CONTEXT_TYPEs = {
  //ALERT
  ADD_ALERT: "ADD_ALERT",
  DECREASE_ALERT_TIME: "DECREASE_ALERT_TIME",
  DELETE_ALERT: "DELETE_ALERT",
  DELETE_ALL_ALERT: "DELETE_ALL_ALERT",
  TOGGLE_ALERT_SHOW: "TOGGLE_ALERT_SHOW",

  //AUTH
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",

  //IMAGE

  USER_IMAGE: "USER_IMAGE",
  PROJECT_IMAGE: "PROJECT_IMAGE",
  BLOG_IMAGE: "BLOG_IMAGE",
  CERTIFICATE_IMAGE: "CERTIFICATE_IMAGE",
  SKILL_IMAGE: "SKILL_IMAGE",
  WORK_IMAGE: "WORK_IMAGE",
  STACK_IMAGE: "STACK_IMAGE",

  //UI

  REFRESH_UI: "REFRESH_UI",
  USER_FORM: "USER_FORM",
  CONFIG_FORM: "CONFIG_FORM",
  PROJECT_FORM: "PROJECT_FORM",
  BLOG_FORM: "BLOG_FORM",
  CERTIFICATE_FORM: "CERTIFICATE_FORM",
  WORK_FORM: "WORK_FORM",
  SKILL_FORM: "SKILL_FORM",
  PRIVATE: "PRIVATE",

  //UTIL
  REFRESH_UTIL: "REFRESH_UTIL",
  DELETE: "DELETE",

  //CONFIG

  PROJECT_TYPES: "PROJECT_TYPES",

  //DELETE
  DELETE_USER: "DELETE_USER",
  DELETE_CONFIG: "DELETE_CONFIG",
  DELETE_PROJECT: "DELETE_PROJECT",
  DELETE_BLOG: "DELETE_BLOG",
  DELETE_SKILL: "DELETE_SKILL",
  DELETE_CERTIFICATE: "DELETE_CERTIFICATE",
  DELETE_WORK: "DELETE_WORK",

  //LANGUAGE
  ENGLISH: "ENGLISH",
  ARABIC: "ARABIC",
  KURDISH: "KURDISH",
};
