export const CONTEXT_TYPEs = {
  //ALERT
  ADD_ALERT: "ADD_ALERT",
  DECREASE_ALERT_TIME: "DECREASE_ALERT_TIME",
  DELETE_ALERT: "DELETE_ALERT",
  DELETE_ALL_ALERT: "DELETE_ALL_ALERT",
  TOGGLE_ALERT_SHOW: "TOGGLE_ALERT_SHOW",

  //UI

  PRIVATE: "PRIVATE",

  //UTIL
  REFRESH_UTIL: "REFRESH_UTIL",

  //LANGUAGE
  ENGLISH: "ENGLISH",
  ARABIC: "ARABIC",
  KURDISH: "KURDISH",
};
