export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Blogs } from "./Blogs";
//export { default as Certificates } from "./Certificates";
//export { default as Contact } from "./Contact";
//export { default as Projects } from "./Projects";
export { default as Services } from "./Services";
export { default as Skills } from "./Skills";
//export { default as Works } from "./Works";
